# Generated by Django 5.1.7 on 2025-10-02 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(choices=[('IBM', 'Institute of Business and Management'), ('ICSLIS', 'Institute of Computing Studies and Library Information Science'), ('IEAS', 'Institute of Education, Arts and Services')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('year_level', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
            ],
        ),
        migrations.CreateModel(
            name='AiRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('student', 'Student'), ('peer', 'Peer')], default='student', max_length=10)),
                ('is_released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='main.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(default='Poor', max_length=50)),
                ('question2', models.CharField(default='Poor', max_length=50)),
                ('question3', models.CharField(default='Poor', max_length=50)),
                ('question4', models.CharField(default='Poor', max_length=50)),
                ('question5', models.CharField(default='Poor', max_length=50)),
                ('question6', models.CharField(default='Poor', max_length=50)),
                ('question7', models.CharField(default='Poor', max_length=50)),
                ('question8', models.CharField(default='Poor', max_length=50)),
                ('question9', models.CharField(default='Poor', max_length=50)),
                ('question10', models.CharField(default='Poor', max_length=50)),
                ('question11', models.CharField(default='Poor', max_length=50)),
                ('question12', models.CharField(default='Poor', max_length=50)),
                ('question13', models.CharField(default='Poor', max_length=50)),
                ('question14', models.CharField(default='Poor', max_length=50)),
                ('question15', models.CharField(default='Poor', max_length=50)),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_by', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evaluator', 'evaluatee')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Dean', 'Dean'), ('Coordinator', 'Coordinator'), ('Faculty', 'Faculty'), ('Admin', 'Admin')], default='Student', max_length=20)),
                ('studentnumber', models.CharField(blank=True, max_length=7, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('institute', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('role', 'Student'), ('studentnumber__isnull', False)), models.Q(('role', 'Student'), _negated=True), _connector='OR'), name='student_fields_required_for_students'), models.CheckConstraint(condition=models.Q(('role', 'Student'), models.Q(('studentnumber__isnull', True), ('course__isnull', True), ('section__isnull', True)), _connector='OR'), name='non_students_cannot_have_student_fields'), models.UniqueConstraint(condition=models.Q(('role', 'Student')), fields=('studentnumber',), name='unique_studentnumber_for_students')],
            },
        ),
    ]
