# Generated by Django 5.1.7 on 2025-10-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionassignment',
            name='role',
            field=models.CharField(choices=[('dean', 'Dean'), ('faculty', 'Faculty'), ('coordinator', 'Coordinator')], default='faculty', max_length=20),
        ),
    ]
