# Generated by Django 5.1.7 on 2025-10-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sectionassignment_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='sectionassignment',
            name='role',
            field=models.CharField(choices=[('dean', 'Dean'), ('faculty', 'Faculty'), ('coordinator', 'Coordinator')], max_length=20),
        ),
    ]
