# Generated by Django 5.1.7 on 2025-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_evaluationresponse_student_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresponse',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Comments/Suggestions'),
        ),
    ]
