# Generated by Django 5.1.7 on 2025-10-14 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_evaluation_failure_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('evaluation_type', models.CharField(choices=[('student', 'Student'), ('peer', 'Peer')], default='student', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('name', 'evaluation_type')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_a_score', models.FloatField(default=0.0)),
                ('category_b_score', models.FloatField(default=0.0)),
                ('category_c_score', models.FloatField(default=0.0)),
                ('category_d_score', models.FloatField(default=0.0)),
                ('total_percentage', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_responses', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=15)),
                ('poor_count', models.IntegerField(default=0)),
                ('unsatisfactory_count', models.IntegerField(default=0)),
                ('satisfactory_count', models.IntegerField(default=0)),
                ('very_satisfactory_count', models.IntegerField(default=0)),
                ('outstanding_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('evaluation_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evaluationperiod')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-evaluation_period__start_date', 'user__username'],
                'unique_together': {('user', 'evaluation_period', 'section')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_positive', models.BooleanField(default=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evaluationresponse')),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.evaluationresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
