# Generated by Django 5.1.7 on 2025-11-06 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_adminactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationresponse',
            name='submitted_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
