# Generated by Django 5.1.7 on 2025-11-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_add_evaluationresponse_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerEvaluationQuestion',
            fields=[
                ('question_number', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('student', 'Student Evaluation'), ('peer', 'Peer Evaluation')], default='student', max_length=10)),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['evaluation_type', 'question_number'],
                'unique_together': {('evaluation_type', 'question_number')},
            },
        ),
    ]
