# Generated by Django 5.1.7 on 2025-11-11 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_peerevaluationquestion_evaluationquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='EvaluationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('student', 'Student Evaluation'), ('peer', 'Peer Evaluation')], default='student', max_length=10)),
                ('category_a_score', models.FloatField(default=0.0)),
                ('category_b_score', models.FloatField(default=0.0)),
                ('category_c_score', models.FloatField(default=0.0)),
                ('category_d_score', models.FloatField(default=0.0)),
                ('total_percentage', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_responses', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=15)),
                ('poor_count', models.IntegerField(default=0)),
                ('unsatisfactory_count', models.IntegerField(default=0)),
                ('satisfactory_count', models.IntegerField(default=0)),
                ('very_satisfactory_count', models.IntegerField(default=0)),
                ('outstanding_count', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('period_start_date', models.DateTimeField(blank=True, null=True)),
                ('period_end_date', models.DateTimeField(blank=True, null=True)),
                ('evaluation_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='main.evaluationperiod')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='main.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start_date', 'user__username'],
                'indexes': [models.Index(fields=['user', '-period_start_date'], name='main_evalua_user_id_deefb8_idx'), models.Index(fields=['evaluation_type', '-period_start_date'], name='main_evalua_evaluat_5bb7e9_idx')],
                'unique_together': {('user', 'evaluation_period', 'section')},
            },
        ),
    ]
