# Generated by Django 5.1.7 on 2025-11-18 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_add_evaluation_period_to_responses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='main.evaluationperiod'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='evaluation_type',
            field=models.CharField(choices=[('student', 'Student'), ('peer', 'Peer')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='priority',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='section_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['user', 'evaluation_period'], name='main_aireco_user_id_28bec1_idx'),
        ),
    ]
