# Generated by Django 5.1.7 on 2025-11-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sync_evaluation_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresponse',
            name='question16',
            field=models.CharField(default='Poor', max_length=50),
        ),
        migrations.AddField(
            model_name='evaluationresponse',
            name='question17',
            field=models.CharField(default='Poor', max_length=50),
        ),
        migrations.AddField(
            model_name='evaluationresponse',
            name='question18',
            field=models.CharField(default='Poor', max_length=50),
        ),
        migrations.AddField(
            model_name='evaluationresponse',
            name='question19',
            field=models.CharField(default='Poor', max_length=50),
        ),
    ]
