# Generated by Django 5.1.7 on 2025-12-11 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_evaluation_evaluator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpwardEvaluationQuestion',
            fields=[
                ('question_number', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='UpwardEvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('question1', models.CharField(default='Poor', max_length=50)),
                ('question2', models.CharField(default='Poor', max_length=50)),
                ('question3', models.CharField(default='Poor', max_length=50)),
                ('question4', models.CharField(default='Poor', max_length=50)),
                ('question5', models.CharField(default='Poor', max_length=50)),
                ('question6', models.CharField(default='Poor', max_length=50)),
                ('question7', models.CharField(default='Poor', max_length=50)),
                ('question8', models.CharField(default='Poor', max_length=50)),
                ('question9', models.CharField(default='Poor', max_length=50)),
                ('question10', models.CharField(default='Poor', max_length=50)),
                ('question11', models.CharField(default='Poor', max_length=50)),
                ('question12', models.CharField(default='Poor', max_length=50)),
                ('question13', models.CharField(default='Poor', max_length=50)),
                ('question14', models.CharField(default='Poor', max_length=50)),
                ('question15', models.CharField(default='Poor', max_length=50)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Additional Comments/Suggestions')),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upward_evaluated_by', to=settings.AUTH_USER_MODEL)),
                ('evaluation_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.evaluationperiod')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upward_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evaluator', 'evaluatee', 'evaluation_period')},
            },
        ),
    ]
