# Generated by Django 5.1.7 on 2025-12-14 04:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_deanevaluationquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUpwardEvaluationQuestion',
            fields=[
                ('question_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('question_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='evaluation_type',
            field=models.CharField(choices=[('student', 'Student'), ('peer', 'Peer'), ('upward', 'Upward'), ('dean', 'Dean'), ('student_upward', 'Student Upward')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_type',
            field=models.CharField(choices=[('student', 'Student'), ('peer', 'Peer'), ('upward', 'Upward'), ('dean', 'Dean'), ('student_upward', 'Student Upward')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluationhistory',
            name='evaluation_type',
            field=models.CharField(choices=[('student', 'Student Evaluation'), ('peer', 'Peer Evaluation'), ('upward', 'Upward Evaluation'), ('dean', 'Dean Evaluation'), ('student_upward', 'Student Upward Evaluation')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluationperiod',
            name='evaluation_type',
            field=models.CharField(choices=[('student', 'Student'), ('peer', 'Peer'), ('upward', 'Upward'), ('dean', 'Dean'), ('student_upward', 'Student Upward')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluationquestion',
            name='evaluation_type',
            field=models.CharField(choices=[('student', 'Student Evaluation'), ('peer', 'Peer Evaluation'), ('upward', 'Upward Evaluation'), ('dean', 'Dean Evaluation'), ('student_upward', 'Student Upward Evaluation')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentUpwardEvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('question1', models.CharField(default='Poor', max_length=50)),
                ('question2', models.CharField(default='Poor', max_length=50)),
                ('question3', models.CharField(default='Poor', max_length=50)),
                ('question4', models.CharField(default='Poor', max_length=50)),
                ('question5', models.CharField(default='Poor', max_length=50)),
                ('question6', models.CharField(default='Poor', max_length=50)),
                ('question7', models.CharField(default='Poor', max_length=50)),
                ('question8', models.CharField(default='Poor', max_length=50)),
                ('question9', models.CharField(default='Poor', max_length=50)),
                ('question10', models.CharField(default='Poor', max_length=50)),
                ('question11', models.CharField(default='Poor', max_length=50)),
                ('question12', models.CharField(default='Poor', max_length=50)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Additional Comments/Suggestions')),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_upward_evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('evaluation_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.evaluationperiod')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_upward_evaluations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evaluator', 'evaluatee', 'evaluation_period')},
            },
        ),
    ]
